version: '2.1'

services:

  consul:
    build:
        context: consul/.
        dockerfile: Dockerfile
    hostname: consul
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500

  fabio:
    build:
      context: fabio/
      dockerfile: Dockerfile
    hostname: fabio
    ports:
      - 9998:9998
      - 9999:9999
    links:
      - consul

  registrator:
    image: gliderlabs/registrator:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    links:
      - consul
    entrypoint:
      - registrator
      - "-ip=172.24.48.1"
      - consul://consul:8500

  webapi:
    build:
      context: webapi/
      dockerfile: Dockerfile
    ports:
      - 5000
    links:
      - consul
    environment:
      - SERVICE_TAGS=urlprefix-/classic strip=/classic
      - SERVICE_5000_CHECK_HTTP=/api/values
      - SERVICE_5000_CHECK_INTERVAL=15s
      - SERVICE_5000_CHECK_TIMEOUT=1s

  webapi-native:
    build:
      context: webapi-nativecalls/
      dockerfile: Dockerfile
    ports:
      - 5000
    links:
      - consul
    environment:
      - SERVICE_TAGS=urlprefix-/native strip=/native
      - SERVICE_5000_CHECK_HTTP=/api/values
      - SERVICE_5000_CHECK_INTERVAL=15s
      - SERVICE_5000_CHECK_TIMEOUT=1s
