version: '2.1'

services:

  consul:
    build:
        context: consul/.
        dockerfile: Dockerfile
    hostname: consul
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500



  registrator:
    image: gliderlabs/registrator:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    links:
      - consul
    entrypoint:
      - registrator
      - consul://consul:8500

  webapi:
    build:
      context: webapi/
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    links:
      - consul
    volumes:
      - ./webapi/:/app

  webapi-native:
    build:
      context: webapi-nativecalls/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    links:
      - consul
    volumes:
      - ./webapi-nativecalls/:/app
